CVP-1596: Fix date period filters
icanbwell/fhir-server pull request #789
Opened 2023-01-10 11:08 UTC by anmolmittal1

2023-01-11 01:55 UTC, imranq2 approved these changes

2023-01-11 10:58 UTC, 007sunny requested changes

2023-01-11 10:58 UTC, 007sunny commented on src/operations/query/filters/dateTime.js
> +function datetimePeriodQueryBuilder({ dateQueryItem, fieldName }) {
All query builders are in the file `querybuilder.util.js`. We should move this as well.

2023-01-11 10:58 UTC, 007sunny commented on src/tests/searchParameters/search_by_period/fixtures/Observation/observation1.json
> +{
We should add multiple observations to represent all kinds of data in the DB with respect to datetimes for observation resource.

2023-01-12 08:55 UTC, 007sunny approved these changes

2023-01-12 08:58 UTC, merged