CVP-1597 updated search operation to raise error if query parameter i…
icanbwell/fhir-server pull request #790
Opened 2023-01-10 13:10 UTC by mintusah25

Changes:

1. r4.js -> Updated buildR4SearchQuery to raise an error when the query parameter is unrecognized.
2. get_all_args.js -> Stored handling passed in the header in arguments to specify the type of search to be conducted.
3. Updated test cases.

2023-01-11 01:57 UTC, imranq2 approved these changes
just fix all the broken unit tests

2023-01-11 01:57 UTC, imranq2 requested changes
thanks.  please fix the unit tests.

2023-01-11 14:38 UTC, anmolmittal1 requested changes

2023-01-11 14:38 UTC, anmolmittal1 commented on src/constants.js
> +        'source', 'id', 'id:above', 'id:below', 'onset_date', '_bundle', '_sort', '_count', '_useTwoStepOptimization',
Do we need id:below, id:above etc now?

2023-01-11 14:38 UTC, anmolmittal1 commented on src/operations/query/r4.js
> +                    throw new NotFoundError(`${queryParameter} is not a parameter for ${resourceType}`);
This should be a BadRequestError

2023-01-11 14:38 UTC, anmolmittal1 commented on src/operations/query/r4.js
> +        const specifiedQueryParams = SPECIFIED_QUERY_PARAMS;
Why is the import assigned to a local constant?

2023-01-12 13:48 UTC, anmolmittal1 requested changes

2023-01-12 14:26 UTC, anmolmittal1 approved these changes

2023-01-13 07:46 UTC, 007sunny approved these changes

2023-01-17 15:52 UTC, imranq2 approved these changes

2023-01-18 05:46 UTC, merged