CVP-1612 updated flow for address field types to use addressQueryBuilder
icanbwell/fhir-server pull request #797
Opened 2023-01-13 12:08 UTC by mintusah25

Changes:

1. string.js - Updated filtering logic to use addressQueryBuilder() for searching on Address.
2. Created test cases specifically for search_by_address.

2023-01-13 13:21 UTC, anmolmittal1 requested changes

2023-01-13 13:21 UTC, anmolmittal1 commented on src/tests/searchParameters/searchByAddress/searchByAddress.test.js
> +            expect(resp).toHaveResponse(expectedPersonResources2);
1. Add test case for invalid search
2. Add test for postal code as well

2023-01-13 13:21 UTC, anmolmittal1 commented on src/tests/searchParameters/searchByAddress/fixtures/expected/expectedSearchByAddressCity.json
> +
Fix this invalid EOF

2023-01-13 13:21 UTC, anmolmittal1 commented on src/tests/searchParameters/searchByAddress/fixtures/Person/person1.json
> +            },
1. format all json files with 2 space indentation
2. Can we create a single bundle for all the patients?

2023-01-16 08:48 UTC, 007sunny commented on src/operations/query/filters/string.js
> +    // If he field is adress, use address query builder to apply the search in all address attributes
Typos

2023-01-16 09:47 UTC, 007sunny approved these changes

2023-01-16 10:20 UTC, anmolmittal1 approved these changes

2023-01-16 10:24 UTC, merged